const fs = require("fs");
const content = fs.readFileSync("./day8.txt", "utf8");

const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

function findAntinodes(input) {}

console.log(findAntinodes(input)); // Should output 14
